CREATE TABLE listings (
    id BIGINT PRIMARY KEY NOT NULL,
    listing_url VARCHAR,
    scrape_id BIGINT,
    last_scraped DATE,
    source VARCHAR,
    name VARCHAR,
    description TEXT,
    neighborhood_overview TEXT,
    picture_url VARCHAR,
    host_id INTEGER,
    host_url VARCHAR,
    host_name VARCHAR,
    host_since DATE,
    host_location VARCHAR,
    host_about TEXT,
    host_response_time VARCHAR,
    host_response_rate VARCHAR,
    host_acceptance_rate VARCHAR,
    host_is_superhost BOOLEAN,
    host_thumbnail_url VARCHAR,
    host_picture_url VARCHAR,
    host_neighbourhood VARCHAR,
    host_listings_count INTEGER,
    host_total_listings_count INTEGER,
    host_verifications VARCHAR,
    host_has_profile_pic BOOLEAN,
    host_identity_verified BOOLEAN,
    neighbourhood VARCHAR,
    neighbourhood_cleansed VARCHAR,
    neighbourhood_group_cleansed VARCHAR,
    latitude DECIMAL,
    longitude DECIMAL,
    property_type VARCHAR,
    room_type VARCHAR,
    accommodates INTEGER,
    bathrooms DECIMAL,
    bathrooms_text VARCHAR,
    bedrooms INTEGER,
    beds INTEGER,
    amenities VARCHAR,
    price VARCHAR,
    minimum_nights INTEGER,
    maximum_nights INTEGER,
    minimum_minimum_nights INTEGER,
    maximum_minimum_nights INTEGER,
    minimum_maximum_nights INTEGER,
    maximum_maximum_nights INTEGER,
    minimum_nights_avg_ntm DECIMAL,
    maximum_nights_avg_ntm DECIMAL,
    calendar_updated TIMESTAMP,
    has_availability BOOLEAN,
    availability_30 INTEGER,
    availability_60 INTEGER,
    availability_90 INTEGER,
    availability_365 INTEGER,
    calendar_last_scraped DATE,
    number_of_reviews INTEGER,
    number_of_reviews_ltm INTEGER,
    number_of_reviews_l30d INTEGER,
    first_review DATE,
    last_review DATE,
    review_scores_rating DECIMAL,
    review_scores_accuracy DECIMAL,
    review_scores_cleanliness DECIMAL,
    review_scores_checkin DECIMAL,
    review_scores_communication DECIMAL,
    review_scores_location DECIMAL,
    review_scores_value DECIMAL,
    license VARCHAR,
    instant_bookable BOOLEAN,
    calculated_host_listings_count INTEGER,
    calculated_host_listings_count_entire_homes INTEGER,
    calculated_host_listings_count_private_rooms INTEGER,
    calculated_host_listings_count_shared_rooms INTEGER,
    reviews_per_month DECIMAL
);

CREATE TABLE reviews (
    listing_id BIGINT REFERENCES listings(id),
    id BIGINT PRIMARY KEY,
    date DATE,
    reviewer_id INTEGER,
    reviewer_name VARCHAR(500),
    comments TEXT
);

CREATE TABLE calendar (
    listing_id BIGINT REFERENCES listings(id) NOT NULL,
    date DATE NOT NULL,
    available BOOLEAN NOT NULL,
    price VARCHAR,
    adjusted_price DECIMAL,
    minimum_nights INTEGER,
    maximum_nights INTEGER NOT NULL,
    PRIMARY KEY (listing_id, date)
);